<?xml version="1.0"?>
<!DOCTYPE tv [
<!-- DTD for TV listings http://xmltv.cvs.sourceforge.net/viewvc/xmltv/xmltv/xmltv.dtd --><!ELEMENT tv (channel* , programme*)>
<!ATTLIST tv date CDATA #IMPLIED>
<!ATTLIST tv source-info-url CDATA #IMPLIED>
<!ATTLIST tv source-info-name CDATA #IMPLIED>
<!ATTLIST tv source-data-url CDATA #IMPLIED>
<!ATTLIST tv generator-info-name CDATA #IMPLIED>
<!ATTLIST tv generator-info-url CDATA #IMPLIED>
<!ELEMENT channel (display-name+ , icon* , url*)>
<!ATTLIST channel id CDATA #REQUIRED>
<!ELEMENT display-name (#PCDATA)>
<!ATTLIST display-name lang CDATA #IMPLIED>
<!ELEMENT url (#PCDATA)>
<!ELEMENT programme (title+ , sub-title* , desc* , credits? , date? , category* , keyword* , language? , orig-language? , length? , icon* , url* , country* , episode-num* , video? , audio? , previously-shown? , premiere? , last-chance? , new? , subtitles* , rating* , star-rating* , review*)>
<!ATTLIST programme start CDATA #REQUIRED>
<!ATTLIST programme stop CDATA #IMPLIED>
<!ATTLIST programme pdc-start CDATA #IMPLIED>
<!ATTLIST programme vps-start CDATA #IMPLIED>
<!ATTLIST programme showview CDATA #IMPLIED>
<!ATTLIST programme videoplus CDATA #IMPLIED>
<!ATTLIST programme channel CDATA #REQUIRED>
<!ATTLIST programme clumpidx CDATA "0/1">
<!ELEMENT title (#PCDATA)>
<!ATTLIST title lang CDATA #IMPLIED>
<!ELEMENT sub-title (#PCDATA)>
<!ATTLIST sub-title lang CDATA #IMPLIED>
<!ELEMENT desc (#PCDATA)>
<!ATTLIST desc lang CDATA #IMPLIED>
<!ELEMENT credits (director* , actor* , writer* , adapter* , producer* , composer* , editor* , presenter* , commentator* , guest*)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT actor (#PCDATA)>
<!ATTLIST actor role CDATA #IMPLIED>
<!ELEMENT writer (#PCDATA)>
<!ELEMENT adapter (#PCDATA)>
<!ELEMENT producer (#PCDATA)>
<!ELEMENT composer (#PCDATA)>
<!ELEMENT editor (#PCDATA)>
<!ELEMENT presenter (#PCDATA)>
<!ELEMENT commentator (#PCDATA)>
<!ELEMENT guest (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ATTLIST category lang CDATA #IMPLIED>
<!ELEMENT keyword (#PCDATA)>
<!ATTLIST keyword lang CDATA #IMPLIED>
<!ELEMENT language (#PCDATA)>
<!ATTLIST language lang CDATA #IMPLIED>
<!ELEMENT orig-language (#PCDATA)>
<!ATTLIST orig-language lang CDATA #IMPLIED>
<!ELEMENT length (#PCDATA)>
<!ATTLIST length units (seconds | minutes | hours) #REQUIRED>
<!ELEMENT icon EMPTY>
<!ATTLIST icon src CDATA #REQUIRED>
<!ATTLIST icon width CDATA #IMPLIED>
<!ATTLIST icon height CDATA #IMPLIED>
<!ELEMENT value (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ATTLIST country lang CDATA #IMPLIED>
<!ELEMENT episode-num (#PCDATA)>
<!ATTLIST episode-num system CDATA "onscreen">
<!ELEMENT video (present? , colour? , aspect? , quality?)>
<!ELEMENT present (#PCDATA)>
<!ELEMENT colour (#PCDATA)>
<!ELEMENT aspect (#PCDATA)>
<!ELEMENT quality (#PCDATA)>
<!ELEMENT audio (present? , stereo?)>
<!ELEMENT stereo (#PCDATA)>
<!ELEMENT previously-shown EMPTY>
<!ATTLIST previously-shown start CDATA #IMPLIED>
<!ATTLIST previously-shown channel CDATA #IMPLIED>
<!ELEMENT premiere (#PCDATA)>
<!ATTLIST premiere lang CDATA #IMPLIED>
<!ELEMENT last-chance (#PCDATA)>
<!ATTLIST last-chance lang CDATA #IMPLIED>
<!ELEMENT new EMPTY>
<!ELEMENT subtitles (language)?>
<!ATTLIST subtitles type (teletext | onscreen | deaf-signed) #IMPLIED>
<!ELEMENT rating (value , icon*)>
<!ATTLIST rating system CDATA #IMPLIED>
<!ELEMENT star-rating (value , icon*)>
<!ATTLIST star-rating system CDATA #IMPLIED>
<!ELEMENT review (#PCDATA)>
<!ATTLIST review type (text | url) #REQUIRED>
<!ATTLIST review source CDATA #IMPLIED>
<!ATTLIST review reviewer CDATA #IMPLIED>
<!ATTLIST review lang CDATA #IMPLIED>
]>
<tv source-info-name="sonhp" source-info-url="http://hoangphison.com" source-data-url="" generator-info-name="jaylinski/xmltv" generator-info-url="https://github.com/jaylinski/xmltv">
  <channel id="vtv1">
    <display-name lang="en">VTV1 HD</display-name>
    <icon src="https://i.imgur.com/te4Rb7f.png" width="" height=""/>
  </channel>
  <channel id="vtv2">
    <display-name lang="en">VTV2 HD</display-name>
    <icon src="https://i.imgur.com/KmngEnt.png" width="" height=""/>
  </channel>
  <channel id="vtv3">
    <display-name lang="en">VTV3 HD</display-name>
    <icon src="https://i.imgur.com/yNiXZri.png" width="" height=""/>
  </channel>
  <channel id="vtv4">
    <display-name lang="en">VTV4 HD</display-name>
    <icon src="https://i.imgur.com/WG3Wi0q.png" width="" height=""/>
  </channel>
  <channel id="vtv5">
    <display-name lang="en">VTV5 HD</display-name>
    <icon src="https://i.imgur.com/lOvwbNQ.png" width="" height=""/>
  </channel>
  <channel id="vtv6">
    <display-name lang="en">VTV6 HD</display-name>
    <icon src="https://i.imgur.com/QI4bFvX.png" width="" height=""/>
  </channel>
  <channel id="vtv7">
    <display-name lang="en">VTV7 HD</display-name>
    <icon src="https://i.imgur.com/z8m5lWk.png" width="" height=""/>
  </channel>
  <channel id="vtv8">
    <display-name lang="en">VTV8 HD</display-name>
    <icon src="https://i.imgur.com/mIjvO6X.png" width="" height=""/>
  </channel>
  <channel id="vtv9">
    <display-name lang="en">VTV9 HD</display-name>
    <icon src="https://i.imgur.com/GDP5zVb.png" width="" height=""/>
  </channel>
  <channel id="axn">
    <display-name lang="en">AXN HD</display-name>
    <icon src="https://i.imgur.com/5Gtp7WP.png" width="" height=""/>
  </channel>
  <channel id="hbo">
    <display-name lang="en">HBO HD</display-name>
    <icon src="https://i.imgur.com/6YSLw8h.png" width="" height=""/>
  </channel>
  <channel id="max_by_hbo">
    <display-name lang="en">Max by HBO</display-name>
    <icon src="https://i.imgur.com/PklWJDL.png" width="" height=""/>
  </channel>
  <channel id="animal_planet">
    <display-name lang="en">Animal Planet</display-name>
    <icon src="https://i.imgur.com/9t7FsCk.png" width="" height=""/>
  </channel>
  <channel id="cartoon_network">
    <display-name lang="en">Cartoon Network HD</display-name>
    <icon src="https://i.imgur.com/nzvNMfP.png" width="" height=""/>
  </channel>
  <channel id="discovery_asia">
    <display-name lang="en">Discovery Asia HD</display-name>
    <icon src="https://i.imgur.com/blEhr2T.png" width="" height=""/>
  </channel>
  <channel id="discovery">
    <display-name lang="en">Discovery Channel HD</display-name>
    <icon src="https://i.imgur.com/fXuxFbz.png" width="" height=""/>
  </channel>
  <channel id="fox_life">
    <display-name lang="en">FOX Life</display-name>
    <icon src="https://i.imgur.com/8COzEQg.png" width="" height=""/>
  </channel>
  <channel id="fox_movies">
    <display-name lang="en">FOX Movies</display-name>
    <icon src="https://i.imgur.com/1bzBhnP.png" width="" height=""/>
  </channel>
  <channel id="fox_sports">
    <display-name lang="en">FOX Sports HD</display-name>
    <icon src="https://i.imgur.com/JsFd6Nl.png" width="" height=""/>
  </channel>
  <channel id="fox_sports2">
    <display-name lang="en">FOX Sports 2 HD</display-name>
    <icon src="https://i.imgur.com/acCilxO.png" width="" height=""/>
  </channel>
  <channel id="fox_sports3">
    <display-name lang="en">FOX Sports 3 HD</display-name>
    <icon src="https://i.imgur.com/dhRuUbt.png" width="" height=""/>
  </channel>
  <channel id="disney_channel">
    <display-name lang="en">Disney Channel</display-name>
    <icon src="https://i.imgur.com/06F6gjj.png" width="" height=""/>
  </channel>
  <channel id="disney_junior">
    <display-name lang="en">Disney Junior</display-name>
    <icon src="https://i.imgur.com/ZUBEPXt.png" width="" height=""/>
  </channel>
  <channel id="mtv_asia">
    <display-name lang="en">MTV Asia</display-name>
    <icon src="https://i.imgur.com/gpWosop.png" width="" height=""/>
  </channel>
  <channel id="channel_v">
    <display-name lang="en">Channel V</display-name>
    <icon src="https://i.imgur.com/BT8eRjq.png" width="" height=""/>
  </channel>
  <channel id="diva">
    <display-name lang="en">DIVA</display-name>
    <icon src="https://i.imgur.com/OJNm5Vt.png" width="" height=""/>
  </channel>
  <channel id="da_vinci_kids">
    <display-name lang="en">Da Vinci Kids</display-name>
    <icon src="https://i.imgur.com/ZkEEeM9.png" width="" height=""/>
  </channel>
  <channel id="asian_food_channel">
    <display-name lang="en">Asian Food Channel</display-name>
    <icon src="https://i.imgur.com/rQ3Sgrn.png" width="" height=""/>
  </channel>
  <channel id="outdoor_channel">
    <display-name lang="en">Outdoor Channel</display-name>
    <icon src="https://i.imgur.com/Z3xc8p1.png" width="" height=""/>
  </channel>
  <channel id="fashion_tv">
    <display-name lang="en">Fashion TV</display-name>
    <icon src="https://i.imgur.com/Zyy11Cs.png" width="" height=""/>
  </channel>
  <channel id="fox">
    <display-name lang="en">FOX HD</display-name>
    <icon src="https://i.imgur.com/cwVCPqN.png" width="" height=""/>
  </channel>
  <channel id="national_geographic">
    <display-name lang="en">National Geographic HD</display-name>
    <icon src="https://i.imgur.com/cjx78kt.png" width="" height=""/>
  </channel>
  <channel id="blue_ant_entertainment">
    <display-name lang="en">Blue Ant Entertainment</display-name>
    <icon src="https://i.imgur.com/BaZuGNL.png" width="" height=""/>
  </channel>
  <channel id="blue_ant_extreme">
    <display-name lang="en">Blue Ant Extreme</display-name>
    <icon src="https://i.imgur.com/EUHDtZ5.png" width="" height=""/>
  </channel>
  <channel id="warner_tv_hd">
    <display-name lang="en">Warner TV HD</display-name>
    <icon src="https://i.imgur.com/z8Cm35k.png" width="" height=""/>
  </channel>
  <channel id="tlc">
    <display-name lang="en">TLC (Travel &amp; Living)</display-name>
    <icon src="https://i.imgur.com/amlBPub.png" width="" height=""/>
  </channel>
  <channel id="red_by_hbo">
    <display-name lang="en">Red by HBO</display-name>
    <icon src="https://i.imgur.com/S3LHf04.png" width="" height=""/>
  </channel>
  <channel id="nhk_world">
    <display-name lang="en">NHK World</display-name>
    <icon src="https://i.imgur.com/OV5nhkM.png" width="" height=""/>
  </channel>
  <channel id="bbc_earth">
    <display-name lang="en">BBC EARTH</display-name>
    <icon src="https://i.imgur.com/3sQunND.png" width="" height=""/>
  </channel>
  <channel id="bbc_lifestyle">
    <display-name lang="en">BBC LIFESTYLE</display-name>
    <icon src="https://i.imgur.com/wwTUVYP.png" width="" height=""/>
  </channel>
  <channel id="bbc_world_news">
    <display-name lang="en">BBC WORLD NEWS</display-name>
    <icon src="https://i.imgur.com/9ZqIRg1.png" width="" height=""/>
  </channel>
  <channel id="baby_tv_hd">
    <display-name lang="en">Baby TV HD</display-name>
    <icon src="https://i.imgur.com/s28XuHs.png" width="" height=""/>
  </channel>
  <channel id="abc_australia">
    <display-name lang="en">ABC AUSTRALIA</display-name>
    <icon src="https://i.imgur.com/0OrWtJm.png" width="" height=""/>
  </channel>
  <channel id="kix_hd">
    <display-name lang="en">KIX HD</display-name>
    <icon src="https://i.imgur.com/CVxACz9.png" width="" height=""/>
  </channel>
  <channel id="cinema_world_hd">
    <display-name lang="en">CINEMA WORLD HD</display-name>
    <icon src="https://i.imgur.com/KcEAjUh.png" width="" height=""/>
  </channel>
  <channel id="htv1">
    <display-name lang="en">HTV1</display-name>
    <icon src="https://i.imgur.com/BvjmYtr.png" width="" height=""/>
  </channel>
  <channel id="htv2">
    <display-name lang="en">HTV2 HD</display-name>
    <icon src="https://i.imgur.com/12qnM2B.png" width="" height=""/>
  </channel>
  <channel id="htv3">
    <display-name lang="en">HTV3</display-name>
    <icon src="https://i.imgur.com/8GOohTX.png" width="" height=""/>
  </channel>
  <channel id="htv4">
    <display-name lang="en">HTV4</display-name>
    <icon src="https://i.imgur.com/JBNgrHU.png" width="" height=""/>
  </channel>
  <channel id="htv7">
    <display-name lang="en">HTV7 HD</display-name>
    <icon src="https://i.imgur.com/EPZzYTx.png" width="" height=""/>
  </channel>
  <channel id="htv9">
    <display-name lang="en">HTV9 HD</display-name>
    <icon src="https://i.imgur.com/vMxj1BX.png" width="" height=""/>
  </channel>
  <channel id="htvc_phim_hd">
    <display-name lang="en">HTVC Phim HD</display-name>
    <icon src="https://i.imgur.com/qQSl5rD.png" width="" height=""/>
  </channel>
  <channel id="htvc_gia_dinh">
    <display-name lang="en">HTVC Gia &#x110;&#xEC;nh</display-name>
    <icon src="https://i.imgur.com/EAv5N7c.png" width="" height=""/>
  </channel>
  <channel id="htvc_du_lich_cuoc_song">
    <display-name lang="en">HTVC Du L&#x1ECB;ch &amp; &#x110;&#x1EDD;i S&#x1ED1;ng</display-name>
    <icon src="https://i.imgur.com/GWGhPu7.png" width="" height=""/>
  </channel>
  <channel id="htvc_phu_nu">
    <display-name lang="en">HTVC Ph&#x1EE5; N&#x1EEF;</display-name>
    <icon src="https://i.imgur.com/pTuBwDS.png" width="" height=""/>
  </channel>
  <channel id="htvc_thuan_viet_hd">
    <display-name lang="en">HTVC Thu&#x1EA7;n Vi&#x1EC7;t HD</display-name>
    <icon src="https://i.imgur.com/jOeEfm6.png" width="" height=""/>
  </channel>
  <channel id="htvc_thuan_viet">
    <display-name lang="en">HTVC Thu&#x1EA7;n Vi&#x1EC7;t</display-name>
    <icon src="https://i.imgur.com/qSzadDW.png" width="" height=""/>
  </channel>
  <channel id="htvc_fbnc">
    <display-name lang="en">FBNC HD</display-name>
    <icon src="https://i.imgur.com/Ekn8jdW.png" width="" height=""/>
  </channel>
  <channel id="htvc_coop">
    <display-name lang="en">HTVC CO.OP</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="htv_the_thao">
    <display-name lang="en">HTV Th&#x1EC3; Thao</display-name>
    <icon src="https://i.imgur.com/gSnnXza.png" width="" height=""/>
  </channel>
  <channel id="htvc_vgs_shop">
    <display-name lang="en">HTVC VGS SHOP</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="vtc1">
    <display-name lang="en">VTC1 HD</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="vtc2">
    <display-name lang="en">VTC2 HD</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="vtc3">
    <display-name lang="en">VTC3 HD</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="vtc4_yeah1_family">
    <display-name lang="en">VTC4 Yeah1 Family HD</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="vtc5">
    <display-name lang="en">VTC5 HD</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="vtc6">
    <display-name lang="en">VTC6 HD</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="vtc7_today_tv">
    <display-name lang="en">VTC7 Today TV HD</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="vtc8">
    <display-name lang="en">VTC8</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="vtc9_lets_viet">
    <display-name lang="en">VTC9 Let's Viet HD</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="vtc10">
    <display-name lang="en">VTC10 HD</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="vtc11_kids_tv">
    <display-name lang="en">VTC11 Kids TV</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="vtc12">
    <display-name lang="en">VTC12</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="vtc13">
    <display-name lang="en">VTC13 HD</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="vtc14">
    <display-name lang="en">VTC14 HD</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="vtc16">
    <display-name lang="en">VTC16 HD</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="thvl1">
    <display-name lang="en">THVL1 - V&#x129;nh Long 1 HD</display-name>
    <icon src="https://i.imgur.com/4xBOSHL.png" width="" height=""/>
  </channel>
  <channel id="thvl2">
    <display-name lang="en">THVL2 - V&#x129;nh Long 2 HD</display-name>
    <icon src="https://i.imgur.com/vyaRrX6.png" width="" height=""/>
  </channel>
  <channel id="thvl3">
    <display-name lang="en">THVL3 - V&#x129;nh Long 3 HD</display-name>
    <icon src="https://i.imgur.com/N79gMEd.png" width="" height=""/>
  </channel>
  <channel id="ttxvn">
    <display-name lang="en">TTXVN - Th&#xF4;ng T&#x1EA5;n X&#xE3; VN HD</display-name>
    <icon src="https://i.imgur.com/7uV8top.png" width="" height=""/>
  </channel>
  <channel id="antv">
    <display-name lang="en">ANTV - An Ninh TV HD</display-name>
    <icon src="https://i.imgur.com/5qQzerW.png" width="" height=""/>
  </channel>
  <channel id="nhan_dan_tv">
    <display-name lang="en">Nh&#xE2;n D&#xE2;n TV HD</display-name>
    <icon src="https://i.imgur.com/rswzxzG.png" width="" height=""/>
  </channel>
  <channel id="quoc_hoi_tv">
    <display-name lang="en">Qu&#x1ED1;c H&#x1ED9;i TV HD</display-name>
    <icon src="https://i.imgur.com/IqErj7W.png" width="" height=""/>
  </channel>
  <channel id="quoc_phong_tv">
    <display-name lang="en">QPTV - Qu&#x1ED1;c Ph&#xF2;ng VN HD</display-name>
    <icon src="https://i.imgur.com/yLQfmkW.png" width="" height=""/>
  </channel>
  <channel id="sctv10">
    <display-name lang="en">SCTV10</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="btv9_an_vien">
    <display-name lang="en">BTV9 - An Vi&#xEA;n HD</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="btv6_viet_teen">
    <display-name lang="en">BTV6 - Vi&#x1EC7;t Teen</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="btv10_ncm">
    <display-name lang="en">BTV10 - NCM</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="btv11_sam">
    <display-name lang="en">BTV11 - SAM</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="hanoitv1">
    <display-name lang="en">H&#xE0; N&#x1ED9;i 1 HD</display-name>
    <icon src="https://i.imgur.com/GhJ0JTH.png" width="" height=""/>
  </channel>
  <channel id="hanoitv2">
    <display-name lang="en">H&#xE0; N&#x1ED9;i 2 HD</display-name>
    <icon src="https://i.imgur.com/OogZeGW.png" width="" height=""/>
  </channel>
  <channel id="arirang">
    <display-name lang="en">Arirang</display-name>
    <icon src="https://i.imgur.com/iIrAEGx.png" width="" height=""/>
  </channel>
  <channel id="cnbc">
    <display-name lang="en">CNBC</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="cnn">
    <display-name lang="en">CNN</display-name>
    <icon src="https://i.imgur.com/krupazx.png" width="" height=""/>
  </channel>
  <channel id="vovtv">
    <display-name lang="en">VOV TV</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="hbo">
    <display-name lang="en">HBO HD</display-name>
    <icon src="https://i.imgur.com/6YSLw8h.png" width="" height=""/>
  </channel>
  <channel id="btv4_imovie">
    <display-name lang="en">BTV4 iMovies HD</display-name>
    <icon src="https://i.imgur.com/lWJcLEv.png" width="" height=""/>
  </channel>
  <channel id="sctv2_amc">
    <display-name lang="en">SCTV2 AMC</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="cna_channel_news_asia">
    <display-name lang="en">Channel News Asia - CNA</display-name>
    <icon src="https://i.imgur.com/eyzGJhD.png" width="" height=""/>
  </channel>
  <channel id="tv5monde_asie">
    <display-name lang="en">TV5Monde Asie</display-name>
    <icon src="https://i.imgur.com/JuELCHc.png" width="" height=""/>
  </channel>
  <channel id="france_24">
    <display-name lang="en">France 24</display-name>
    <icon src="https://i.imgur.com/YTlPk6Q.png" width="" height=""/>
  </channel>
  <channel id="kplus1hd">
    <display-name lang="en">K+1 HD (DRM)</display-name>
    <icon src="https://i.imgur.com/4DqLcOH.png" width="" height=""/>
  </channel>
  <channel id="kplusnshd">
    <display-name lang="en">K+NS HD (DRM)</display-name>
    <icon src="https://i.imgur.com/4kKphEM.png" width="" height=""/>
  </channel>
  <channel id="kpluspchd">
    <display-name lang="en">K+PC HD (DRM)</display-name>
    <icon src="https://i.imgur.com/IaG3BQQ.png" width="" height=""/>
  </channel>
  <channel id="kpluspmhd">
    <display-name lang="en">K+PM HD (DRM)</display-name>
    <icon src="https://i.imgur.com/ND1139A.png" width="" height=""/>
  </channel>
  <channel id="hanoicab4_mov">
    <display-name lang="en">MOV - Hanoicab 4</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="hanoicab2_youtv">
    <display-name lang="en">YouTV - Hanoicab 2</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <programme start="20190910180000 +0000" stop="20190910190459 +0000" channel="abc_australia">
    <title lang="en">PARLIAMENT QUESTION TIME</title>
    <desc lang="en"/>
    <date>20190911</date>
  </programme>
  <programme start="20190910190500 +0000" stop="20190910192959 +0000" channel="abc_australia">
    <title lang="en">HOME AND AWAY</title>
    <desc lang="en"/>
    <date>20190911</date>
  </programme>
  <programme start="20190910193000 +0000" stop="20190910195959 +0000" channel="abc_australia">
    <title lang="en">7.30</title>
    <desc lang="en"/>
    <date>20190911</date>
  </programme>
  <programme start="20190910200000 +0000" stop="20190910225959 +0000" channel="abc_australia">
    <title lang="en">NEWS BREAKFAST: EARLY</title>
    <desc lang="en"/>
    <date>20190911</date>
  </programme>
  <programme start="20190910230000 +0000" stop="20190911015959 +0000" channel="abc_australia">
    <title lang="en">ABC NEWS MORNINGS</title>
    <desc lang="en"/>
    <date>20190911</date>
  </programme>
  <programme start="20190911020000 +0000" stop="20190911022959 +0000" channel="abc_australia">
    <title lang="en">ABC NEWS AT NOON</title>
    <desc lang="en"/>
    <date>20190911</date>
  </programme>
  <programme start="20190911023000 +0000" stop="20190911025959 +0000" channel="abc_australia">
    <title lang="en">BTN</title>
    <desc lang="en"/>
    <date>20190911</date>
  </programme>
  <programme start="20190911030000 +0000" stop="20190911032959 +0000" channel="abc_australia">
    <title lang="en">PLAY SCHOOL</title>
    <desc lang="en"/>
    <date>20190911</date>
  </programme>
  <programme start="20190911033000 +0000" stop="20190911033959 +0000" channel="abc_australia">
    <title lang="en">THE WOTWOTS</title>
    <desc lang="en"/>
    <date>20190911</date>
  </programme>
  <programme start="20190911034000 +0000" stop="20190911040459 +0000" channel="abc_australia">
    <title lang="en">ROUND THE TWIST</title>
    <desc lang="en"/>
    <date>20190911</date>
  </programme>
  <programme start="20190911040500 +0000" stop="20190911041459 +0000" channel="abc_australia">
    <title lang="en">STUDY ENGLISH</title>
    <desc lang="en"/>
    <date>20190911</date>
  </programme>
  <programme start="20190911041500 +0000" stop="20190911041959 +0000" channel="abc_australia">
    <title lang="en">ENGLISH BITES</title>
    <desc lang="en"/>
    <date>20190911</date>
  </programme>
  <programme start="20190911042000 +0000" stop="20190911043459 +0000" channel="abc_australia">
    <title lang="en">LIVING ENGLISH</title>
    <desc lang="en"/>
    <date>20190911</date>
  </programme>
  <programme start="20190911043500 +0000" stop="20190911045959 +0000" channel="abc_australia">
    <title lang="en">HOME AND AWAY</title>
    <desc lang="en"/>
    <date>20190911</date>
  </programme>
  <programme start="20190911050000 +0000" stop="20190911055959 +0000" channel="abc_australia">
    <title lang="en">GARDENING AUSTRALIA</title>
    <desc lang="en"/>
    <date>20190911</date>
  </programme>
  <programme start="20190911060000 +0000" stop="20190911065959 +0000" channel="abc_australia">
    <title lang="en">AFTERNOON BRIEFING</title>
    <desc lang="en"/>
    <date>20190911</date>
  </programme>
  <programme start="20190911070000 +0000" stop="20190911075959 +0000" channel="abc_australia">
    <title lang="en">ABC NATIONAL NEWS</title>
    <desc lang="en"/>
    <date>20190911</date>
  </programme>
  <programme start="20190911080000 +0000" stop="20190911085959 +0000" channel="abc_australia">
    <title lang="en">THE DRUM</title>
    <desc lang="en"/>
    <date>20190911</date>
  </programme>
  <programme start="20190911090000 +0000" stop="20190911092959 +0000" channel="abc_australia">
    <title lang="en">HOME AND AWAY</title>
    <desc lang="en"/>
    <date>20190911</date>
  </programme>
  <programme start="20190911093000 +0000" stop="20190911095959 +0000" channel="abc_australia">
    <title lang="en">7.30</title>
    <desc lang="en"/>
    <date>20190911</date>
  </programme>
  <programme start="20190911100000 +0000" stop="20190911114459 +0000" channel="abc_australia">
    <title lang="en">ABC NEWS TONIGHT</title>
    <desc lang="en"/>
    <date>20190911</date>
  </programme>
  <programme start="20190911114500 +0000" stop="20190911115959 +0000" channel="abc_australia">
    <title lang="en">THE BUSINESS</title>
    <desc lang="en"/>
    <date>20190911</date>
  </programme>
  <programme start="20190911120000 +0000" stop="20190911125959 +0000" channel="abc_australia">
    <title lang="en">THE WORLD</title>
    <desc lang="en"/>
    <date>20190911</date>
  </programme>
  <programme start="20190911130000 +0000" stop="20190911135959 +0000" channel="abc_australia">
    <title lang="en">ABC NIGHTLY NEWS</title>
    <desc lang="en"/>
    <date>20190911</date>
  </programme>
  <programme start="20190911140000 +0000" stop="20190911142959 +0000" channel="abc_australia">
    <title lang="en">ABC LATE NEWS</title>
    <desc lang="en"/>
    <date>20190911</date>
  </programme>
  <programme start="20190911143000 +0000" stop="20190911145959 +0000" channel="abc_australia">
    <title lang="en">HOME AND AWAY</title>
    <desc lang="en"/>
    <date>20190911</date>
  </programme>
  <programme start="20190911150000 +0000" stop="20190911152959 +0000" channel="abc_australia">
    <title lang="en">ABC LATE NEWS</title>
    <desc lang="en"/>
    <date>20190911</date>
  </programme>
  <programme start="20190911153000 +0000" stop="20190911162959 +0000" channel="abc_australia">
    <title lang="en">THE DRUM</title>
    <desc lang="en"/>
    <date>20190911</date>
  </programme>
  <programme start="20190911163000 +0000" stop="20190911164459 +0000" channel="abc_australia">
    <title lang="en">ABC NEWS OVERNIGHT</title>
    <desc lang="en"/>
    <date>20190911</date>
  </programme>
  <programme start="20190911164500 +0000" stop="20190911165859 +0000" channel="abc_australia">
    <title lang="en">THE BUSINESS</title>
    <desc lang="en"/>
    <date>20190911</date>
  </programme>
  <programme start="20190910174000 +0000" stop="20190910183459 +0000" channel="animal_planet">
    <title lang="en">C&#xD4;NG VI&#xCA;N THU&#x1EF6; SINH T&#x1EAC;P 2: T&#x1EAC;P 2</title>
    <desc lang="en"/>
    <date>20190911</date>
  </programme>
  <programme start="20190910183500 +0000" stop="20190910202459 +0000" channel="animal_planet">
    <title lang="en">EVAN V&#xC0; NI&#x1EC0;M VUI N&#x1A0;I HOANG D&#xC3; T&#x1EAC;P 5: T&#x1EAC;P 5</title>
    <desc lang="en"/>
    <date>20190911</date>
  </programme>
  <programme start="20190910202500 +0000" stop="20190910211959 +0000" channel="animal_planet">
    <title lang="en">QU&#xC1;I V&#x1EAC;T TRONG T&#xD4;I (PH&#x1EA6;N 5) T&#x1EAC;P 7: T&#x1EAC;P 7</title>
    <desc lang="en"/>
    <date>20190911</date>
  </programme>
  <programme start="20190910212000 +0000" stop="20190910221459 +0000" channel="animal_planet">
    <title lang="en">M&#xC8;O C&#x1EE6;A T&#xD4;I T&#x1EDA;I T&#x1EEA; &#x110;&#x1ECA;A NG&#x1EE4;C T&#x1EAC;P 5: T&#x1EAC;P 5</title>
    <desc lang="en"/>
    <date>20190911</date>
  </programme>
  <programme start="20190910221500 +0000" stop="20190910231459 +0000" channel="animal_planet">
    <title lang="en">CH&#x1ED0;N NGUY HI&#x1EC2;M CH&#x1EBE;T NG&#x1AF;&#x1EDC;I TR&#xCA;N TR&#xC1;I &#x110;&#x1EA4;T T&#x1EAC;P 1: T&#x1EAC;P 1</title>
    <desc lang="en"/>
    <date>20190911</date>
  </programme>
  <programme start="20190910231500 +0000" stop="20190911001459 +0000" channel="animal_planet">
    <title lang="en">CU&#x1ED8;C CHI&#x1EBE;N C&#xC1; VOI (PH&#x1EA6;N 30 T&#x1EAC;P 2: T&#x1EAC;P 2</title>
    <desc lang="en"/>
    <date>20190911</date>
  </programme>
  <programme start="20190911001500 +0000" stop="20190911010959 +0000" channel="animal_planet">
    <title lang="en">NH&#x1EEE;NG SINH V&#x1EAC;T &#x110;&#xC1;NG Y&#xCA;U NH&#x1EA4;T N&#x1AF;&#x1EDA;C M&#x1EF8; (PH&#x1EA6;N 5) T&#x1EAC;P 5: T&#x1EAC;P 5</title>
    <desc lang="en"/>
    <date>20190911</date>
  </programme>
  <programme start="20190911011000 +0000" stop="20190911020459 +0000" channel="animal_planet">
    <title lang="en">GI&#xC1;C QUAN SI&#xCA;U &#x110;&#x1EB2;NG (PH&#x1EA6;N 2) T&#x1EAC;P 6: T&#x1EAC;P 6</title>
    <desc lang="en"/>
    <date>20190911</date>
  </programme>
  <programme start="20190911020500 +0000" stop="20190911025959 +0000" channel="animal_planet">
    <title lang="en">C&#xD4;NG VI&#xCA;N THU&#x1EF6; SINH (T&#x1EAC;P 2)</title>
    <desc lang="en"/>
    <date>20190911</date>
  </programme>
  <programme start="20190911030000 +0000" stop="20190911035459 +0000" channel="animal_planet">
    <title lang="en">EVAN V&#xC0; NI&#x1EC0;M VUI N&#x1A0;I HOANG D&#xC3; (T&#x1EAC;P 5)</title>
    <desc lang="en"/>
    <date>20190911</date>
  </programme>
  <programme start="20190911035500 +0000" stop="20190911044959 +0000" channel="animal_planet">
    <title lang="en">M&#xC8;O C&#x1EE6;A T&#xD4;I T&#x1EDA;I T&#x1EEA; &#x110;&#x1ECA;A NG&#x1EE4;C (T&#x1EAC;P 5)</title>
    <desc lang="en"/>
    <date>20190911</date>
  </programme>
  <programme start="20190911045000 +0000" stop="20190911054459 +0000" channel="animal_planet">